stages:
  prep:
    foreach: ${countries}
    do:
      cmd: python prep.py ${key}
      params:
        - split
      deps:
        - prep.py
        - raw/${key}
      outs:
        - train/${key}
        - test/${key}
  train:
    foreach: ${countries}
    do:
      cmd: python train.py ${key}
      params:
        - countries.${key}.model_params
      deps:
        - train.py
        - train/${key}
      outs:
        - models/${key}
  eval:
    foreach: ${countries}
    do:
      cmd: python eval.py ${key}
      params:
        - countries.${key}.model_params
      deps:
        - eval.py
        - train/${key}
        - test/${key}
        - models/${key}
      metrics:
        - results/${key}.json
