defaults:
  - models@countries.us.model_params: large
  - models@countries.uk.model_params: large
  - models@countries.fr.model_params: small
  - models@countries.es.model_params: small
split: 0.8
countries:
  es:
    name: es
    model_params:
      max_length: 80
